### ISSUE TITLE
Errors with .NEF format files 

### ISSUE THREAD

**Issue by selous123** [karaimer/camera-pipeline-UI#1]
I have tried the codes with .NEF format files in the sample images folders, but errors have been rasied :
"**Missing DNG files**"

Maybe you can provide not only the dng version '.exe' files, 

or load files in matlab codes instead of in the '.exe' files.

Look forward for your reply.

**Comment by karaimer** [comment]
Could you please convert .NEF files using Adobe DNG converter? File types other than DNG should be converted before feeding as input to the program. 

Cheers, 
Hakki
