### ISSUE TITLE
How to use this UI

### ISSUE THREAD

**Issue by kenzoISP** [karaimer/camera-pipeline-UI#2]
Would you kindly tell me how to use this UI for learning Camera Pipeline? I‘m wondering if there are some guidance about the '.m' UI because when i input my picture, it always gone fail. 
Thank you so much

**Comment by karaimer** [comment]
Yes, there is documentation.  Please have a look at the link [here](https://docs.google.com/document/d/1WzeZ-9U4aTuwFpcX-8GgAy0wT9ERF41ltjr-jJ-NMCo/edit?usp=sharing).
