### ISSUE TITLE
got error on matlab2020

### ISSUE THREAD

**Issue by XiaoyuShi97** [karaimer/camera-pipeline-UI#3]
Hi, I tried to run this UI on matlab 2020.
After double click camera_pipeline.fig, the window looks like
![image](https://user-images.githubusercontent.com/25840016/104451510-9d96bd80-55dc-11eb-879b-ae77060bd61f.png)
As you can see, there is no pipeline stages showing on the left.
After clicking run pipeline and load a .dng image, I got
Reference to non-existent field 'radiobutton15'.

Error in camera_pipeline>pushbutton1_Callback (line 135)
    a = [get(handles.radiobutton15,'Value') get(handles.radiobutton16,'Value') get(handles.radiobutton3,'Value') get(handles.radiobutton8,'Value')];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in camera_pipeline (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)camera_pipeline('pushbutton1_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Is this because the matlab I am using is too new?

**Comment by karaimer** [comment]
I'll run on Matlab 2020 and let you know. Thanks for letting me know!

**Comment by karaimer** [comment]
Just tested on Matlab R2019a and it works on that version: 

![image](https://user-images.githubusercontent.com/2944637/104477385-08b9a300-558f-11eb-80f6-f7933f800053.png)

**Comment by XiaoyuShi97** [comment]
Thanks! I see that the non-ui version works well on Matlab2020.

**Comment by XiaoyuShi97** [comment]
The ui version works well on matlab2019a. Thx!

**Comment by karaimer** [comment]
I'm glad to hear that!
