### ISSUE TITLE
question about how to specify stage for dng_validate.exe

### ISSUE THREAD

**Issue by XiaoyuShi97** [karaimer/camera-pipeline-UI#4]
Hi. I see that to get the output of stage 2 and stage 3, the code is the same
        system_command = [fullfile('.','dngOneExeSDK','dng_validate.exe -16 -2 ')  stage2OutputFileName ' ' inputFileName];
I wonder how does dng_validate differentiate these two stages? Are you doing it by setting stageSettings_indicator, and dng_validate checks last line of stageSettings.txt to know which stage it is going to stop?

Thx!

**Comment by XiaoyuShi97** [comment]
A similar question about reloading image back to pipeline. As the document said, when we choose write mode, r, g, b.txt files are saved. Then we convert them to a tiff, work on the tiff and convert the tiff back to three txt files. Then we reopen(?) the GUI, choose stage 11 with read mode. But I am confused that there is no tag in these txt files indicating at which stage we stop. Then when we re-run the pipeline, how does it know which stage it load these r, g, b .txt files to?

Thx!

**Comment by karaimer** [comment]
There is a file named lastStage.txt. I wrote the last stage in the write mode; when the read mode is on, the pipeline checks the lastStage.txt and continues rendering from there.

**Comment by karaimer** [comment]
The difference is the vignetting. I control if the vignetting is applied or not using the wbAndGainSettings.txt file. 

The related part of the C++ code reads this file. Based on the contents of this file, I can make a rendering decision. 

The content of the file is just a four-vector that controls the rendering of the vignetting and the white balancing. 

The first two are used for vignetting, the last two are used for white balancing. 

For example; 
[1     0     0     1] makes vignetting "On", and allows custom white balancing using "Load WB" 
[0     1     1     0] makes vignetting "Off" and uses the camera's AWB decision("As Shot") during rendering.
