### ISSUE TITLE
How to get stage-x to final stage output?

### ISSUE THREAD

**Issue by GopiRajuMatta** [karaimer/camera-pipeline-UI#5]
@karaimer,

Can you please let me know how to use this UI or non-UI to get output, let's say from stage-7 to final stage. Here I want to input my image at the stage-7 and pass it through remaining stages and get the output at the final stage.

Thank you
Gopi

**Comment by karaimer** [comment]
Hi, Gopi, 

Link [here](https://github.com/karaimer/camera-pipeline-nonUI) shows an example for pushing the images back into the pipeline without a UI. 

For the UI version, the [documentation ](https://docs.google.com/document/d/1WzeZ-9U4aTuwFpcX-8GgAy0wT9ERF41ltjr-jJ-NMCo/edit) also shows another example. 

Thanks, 
Hakki

**Comment by GopiRajuMatta** [comment]
Thank you for the response Hakki. I'll look into it.

**Comment by ghost** [comment]
Hello,

Can't this pipeline be used when when size of intermediate image(txt) is different from input size? As it is told in the documentation, it is mentioned that do not use the save button but use write button as image size changes after demosaic stage. In my case, let's say I stopped after demosaic stage and then did some processing which reduced the size of my image and then it was converted to txt to input to the pipeline. In this case, I am not getting expected result. 

Can you please guide me on this regarding how to proceed.

Thank you
Gopi

**Comment by karaimer** [comment]
The pipeline is assuming the image size at each stage is fixed. When the size is reduced due to the demosaic stage, it's expecting a processed input same as the reduced image size. This is the same when you push images back.  

If your processing reduced the size of the image, you can pad with zeros and bring the image size back to the right size at that stage.

**Comment by ghost** [comment]
Sounds great! Will try this out!

**Comment by ghost** [comment]
I tried this out, results are improved but still needs improvement. What if, if I resize image to the same size using some interpolation method and then use that? How that would be different from padding zeros? One more question is that why after demoisacing, size is changing? It should be same as input right!

**Comment by karaimer** [comment]
Depending on your application, you can try your suggestions. Demosaicing can change the size of the image; it depends on the demosaicing algorithm.

**Comment by ghost** [comment]
Hello,

In one of the issues, it was mentioned, "There is a file named lastStage.txt. I wrote the last stage in the write mode; when the read mode is on, the pipeline checks the lastStage.txt and continues rendering from there."
If this is the case, then while loading input image, I can load any image right! But it is mentioned specifically that we should load the same image on which operations are done.

Can you please clarify on this.

Thank you
Gopi

**Comment by karaimer** [comment]
Yes, you can load any image back as long as the image size matches.

**Comment by GopiRajuMatta** [comment]
Thank you for the reply. 

Can you also please clarify(elaborate) on the image size matching. Is it a way that I get same size as input after demosaicing using this pipeline? 

Thank you
Gopi

**Comment by karaimer** [comment]
Once the image is dumped out of the pipeline for external use, the expected image size to push it back is the same as the dumped image at that stage. In this pipeline, the demosaicing algorithm changes the size of the input image.

**Comment by ghost** [comment]
Understood, thank you for the clarification.
